import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "UI/UX Designer (Freelance)",
    company: "Spigen Indonesia",
    logo: "/images/careers/logo spigen.png",
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Freelance",
    start_date: "2024-06",
    end_date: "2024-08",
    industry: "E-Commerce / Mobile Accessories",
    link: "https://spigen.co.id/",
    responsibilities: [
      "Designed a modern and conversion-focused UI for Spigen Indonesia’s product detail and checkout pages to improve user clarity and reduce friction during purchase.",
      "Created responsive interface designs for mobile and desktop, ensuring consistent visual identity across all pages.",
      "Conducted UX audits on the existing website and proposed improvements in navigation structure, product filtering, and purchase flow.",
      "Developed a reusable UI component library in Figma to streamline the design-to-development handoff process.",
      "Collaborated with marketing and development teams to align product visuals, typography, and branding with Spigen’s global design guidelines.",
    ],
    isShow: true,
  },
  {
    position: "UX Researcher",
    company: "Shato Media",
    logo: "/images/careers/shatomedia.png",
    location: "Yogyakarta, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Research Project",
    start_date: "2024-04",
    end_date: "2024-08",
    industry: "Digital Marketing & Creative Production",
    link: "https://shatomedia.com/",
    responsibilities: [
      "Conducted a comprehensive usability evaluation of Shato Media’s website using the System Usability Scale (SUS) and ISO 9241-11 framework.",
      "Identified key usability issues related to navigation, content clarity, visual hierarchy, and task efficiency.",
      "Performed user surveys, heuristic analysis, and task-based testing to gather quantitative and qualitative insights.",
      "Synthesized findings into actionable recommendations to improve user experience and overall website effectiveness.",
      "Collaborated with internal teams to align usability insights with business goals and brand communication strategy.",
    ],
    isShow: true,
  },
  {
    position: "UI/UX Designer",
    company: "ThreeFive Indonesia",
    logo: "/images/careers/threefive.jpg",
    location: "Banyumas, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Freelance Project",
    start_date: "2024-10",
    end_date: "2024-12",
    industry: "Creative Digital Agency",
    link: "https://threefive.co.id/",
    responsibilities: [
      "Designed the complete UI/UX for the ThreeFive Indonesia corporate website, focusing on clear brand communication and visual identity consistency.",
      "Developed user flows, wireframes, and high-fidelity prototypes to improve navigation clarity and content hierarchy.",
      "Conducted competitor benchmarking and usability checks to ensure the interface aligns with industry standards and user expectations.",
      "Collaborated closely with stakeholders to translate business goals into intuitive interface solutions.",
      "Created responsive layouts optimized for desktop and mobile, ensuring seamless experience across all devices.",
    ],
    isShow: true,
  },
  {
  position: "Member of Internal Division",
  company: "Badan Eksekutif Mahasiswa (BEM) FMIKOM UNUGHA",
  logo: "/images/careers/LOGO BEM.png",
  location: "Cilacap, Indonesia 🇮🇩",
  location_type: "Onsite",
  type: "Organization",
  start_date: "2022-12",
  end_date: "2023-12",
  industry: "Student Organization",
  link: "https://www.instagram.com/fmikom.unugha/",
  responsibilities: [
    "Supported internal coordination and communication to maintain organizational stability within BEM FMIKOM.",
    "Assisted in planning, organizing, and executing faculty-level events and student activities.",
    "Facilitated collaboration across departments to ensure smooth operational workflows throughout the organization.",
    "Contributed to administrative tasks, documentation, and internal reporting to support the division's responsibilities."
  ],
  isShow: true,
},
  {
  position: "Member of Communication & Information Division",
  company: "Himpunan Mahasiswa Informatika (HIMAFORTIC)",
  logo: "/images/careers/himafortic.png",
  location: "Cilacap, Indonesia 🇮🇩",
  location_type: "Onsite",
  type: "Organization",
  start_date: "2022-12",
  end_date: "2023-12",
  industry: "Student Organization",
  link: "https://www.instagram.com/himafortic.unugha/",
  responsibilities: [
    "Assisted in managing digital communication channels for HIMAFORTIC, including social media content dissemination and information flow.",
    "Contributed to documentation, publication, and design tasks to support organizational events and programs.",
    "Collaborated with team members to ensure accurate and timely distribution of information to Informatics students.",
    "Helped maintain consistency in branding and visual identity across HIMAFORTIC's digital platforms.",
  ],
  isShow: true,
  },
];
